# Generated by Django 4.2.13 on 2024-06-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='animation',
            field=models.FileField(blank=True, null=True, upload_to='animations/'),
        ),
    ]
