# Generated by Django 4.2.13 on 2024-06-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='csv/'),
        ),
    ]
